# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: run.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trun.proto\"C\n\x07\x43\x41sTRun\x12\x10\n\x08run_name\x18\x01 \x01(\t\x12\x10\n\x08run_type\x18\x02 \x01(\t\x12\x14\n\x05turns\x18\x03 \x03(\x0b\x32\x05.Turn\"5\n\x04Turn\x12\x0f\n\x07turn_id\x18\x01 \x01(\t\x12\x1c\n\tresponses\x18\x02 \x03(\x0b\x32\t.Response\"G\n\x08Response\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\x1f\n\nprovenance\x18\x03 \x03(\x0b\x32\x0b.Provenance\"5\n\nProvenance\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\x62\x06proto3')



_CASTRUN = DESCRIPTOR.message_types_by_name['CAsTRun']
_TURN = DESCRIPTOR.message_types_by_name['Turn']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_PROVENANCE = DESCRIPTOR.message_types_by_name['Provenance']
CAsTRun = _reflection.GeneratedProtocolMessageType('CAsTRun', (_message.Message,), {
  'DESCRIPTOR' : _CASTRUN,
  '__module__' : 'run_pb2'
  # @@protoc_insertion_point(class_scope:CAsTRun)
  })
_sym_db.RegisterMessage(CAsTRun)

Turn = _reflection.GeneratedProtocolMessageType('Turn', (_message.Message,), {
  'DESCRIPTOR' : _TURN,
  '__module__' : 'run_pb2'
  # @@protoc_insertion_point(class_scope:Turn)
  })
_sym_db.RegisterMessage(Turn)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'run_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

Provenance = _reflection.GeneratedProtocolMessageType('Provenance', (_message.Message,), {
  'DESCRIPTOR' : _PROVENANCE,
  '__module__' : 'run_pb2'
  # @@protoc_insertion_point(class_scope:Provenance)
  })
_sym_db.RegisterMessage(Provenance)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CASTRUN._serialized_start=13
  _CASTRUN._serialized_end=80
  _TURN._serialized_start=82
  _TURN._serialized_end=135
  _RESPONSE._serialized_start=137
  _RESPONSE._serialized_end=208
  _PROVENANCE._serialized_start=210
  _PROVENANCE._serialized_end=263
# @@protoc_insertion_point(module_scope)
